version: '3.8'
services:
  web:
    build:
      context: .
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bash -c "rm -f /rails/tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0 -p 4000"
    volumes:
      - .:/rails
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db/grisha_space
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: grisha_space
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
