databases:
  - name: postgres
    ipAllowList: []
    databaseName: grisha_space
    user: grisha_space_user

services:
  - type: web
    name: grisha-space
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false