default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] || 'rails' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '123' %>

development:
  <<: *default
  database: grisha_space_development

test:
  <<: *default
  database: grisha_space_test

production:
  <<: *default
  host: db
  database: <%= ENV['POSTGRES_DB'] %>
